# Generated by Django 2.2.5 on 2019-09-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallpaper",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("source_id", models.CharField(max_length=100)),
                ("last_consumed", models.DateTimeField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="weeblife_wallpaper")),
            ],
            options={"abstract": False, "unique_together": {("source", "source_id")}},
        ),
        migrations.CreateModel(
            name="LoadingAnimation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("source_id", models.CharField(max_length=100)),
                ("last_consumed", models.DateTimeField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="weeblife_loading")),
            ],
            options={"abstract": False, "unique_together": {("source", "source_id")}},
        ),
    ]
