# Generated by Django 2.2.5 on 2019-09-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("weeblife", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="loadinganimation",
            name="image",
            field=models.FileField(upload_to="weeblife_loading"),
        ),
        migrations.AlterField(
            model_name="wallpaper",
            name="image",
            field=models.FileField(upload_to="weeblife_wallpaper"),
        ),
    ]
